// Константы для визуализаций
export const VISUALIZATION_CONSTANTS = {
	NODE_HEIGHT: 30,
	NODE_PADDING: 20,
	MIN_NODE_WIDTH: 50,
	TRANSITION_DURATION: 200,
	TREE_LEVEL_SPACING: 220,
	RADIAL_RADIUS_PADDING: 50,
	TREEMAP_PADDING: 1,
}
